#!/usr/bin/env python3
"""Run riscv-arch-test 4.1.0 (ACT4) self-checking ELFs on PX32 (step 1.8, architectural part).

The ACT4 framework builds the ELFs (Linux: make, uv, Ruby/UDB, Sail 0.13.1 computes the
expected values at build time) from sw/compliance/act4/px32/ (generated by
scripts/compliance/make_act4_config.py). This script only runs them: every ELF goes through
scripts/compliance/elf2mem.py into tb/compliance/tb_compliance.sv (px_core RTL, Icarus).

A test passes only if all of these hold:
  - the bench reports PASS: the ELF stored 1 to the PX32 halt word (RVMODEL_HALT_PASS);
    RVMODEL_HALT_FAIL stores 3
  - the console (RVMODEL_IO_WRITE_STR) shows exactly one "RVCP-SUMMARY: TEST PASSED" line
    and no "RVCP-SUMMARY: TEST FAILED" line (a halt without the summary is not a pass)
  - the simulation ends without bench errors, deadlock, cycle limit or wall-clock limit
Fail closed:
  - the suite checkout is not at the pinned 4.1.0 commit
  - a required group (tests/rv32i/{I,M,Zca,Zicsr,Zifencei}) has no sources, or any source
    has no ELF in --elf-dir (not built counts as a failure, never as skipped)
  - --elf-dir has no MANIFEST.txt (written by setup_act4_wsl.sh), or the manifest's suite
    commit or configuration hashes differ from the pinned commit and the repository's
    sw/compliance/act4/px32 files: the ELFs were built from another configuration
Other ELFs found in --elf-dir (groups the configuration selected beyond the required ones)
are run and reported as informational.
--stress SEED: every test that passes with ideal memory runs again with random bus stalls
(tb_compliance +stress); a failure in either run fails the test.

Outputs: sim/compliance/act4/ (images, logs, traces, results.json, summary.txt).

Usage: python scripts/compliance/run_act4.py --elf-dir DIR [--suite DIR] [--stress SEED]
       python scripts/compliance/run_act4.py --selftest
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts/compliance"))
import run_riscv_tests as rt   # noqa: E402  (bench compile, simulate, tools)

SUITE_COMMIT = "6e8a45123f14cebfb3df151a0e7b849b4389b33b"      # riscv-arch-test 4.1.0
REQUIRED = ["I", "M", "Zca", "Zicsr", "Zifencei"]
HALT, CONSOLE = "100ffff0", "100ffff8"                      # make_act4_config.py
OUT = ROOT / "sim/compliance/act4"
CONFIG = ROOT / "sw/compliance/act4/px32"


def manifest_problems(elf_dir):
    """Differences between the ELF set's manifest and the current configuration files."""
    import hashlib
    mf = elf_dir / "MANIFEST.txt"
    if not mf.is_file():
        return [f"no {mf.name} in {elf_dir}: rebuild with setup_act4_wsl.sh"]
    got = {}
    suite = None
    for ln in mf.read_text().splitlines():
        f = ln.split()
        if len(f) == 2 and f[0] == "suite":
            suite = f[1]
        elif len(f) == 3 and f[0] == "config":
            got[f[1]] = f[2]
    want = {c.name: hashlib.sha256(c.read_bytes().replace(b"\r\n", b"\n")).hexdigest()
            for c in sorted(CONFIG.iterdir()) if c.is_file()}
    probs = [] if suite == SUITE_COMMIT else [f"manifest suite {suite}, expected {SUITE_COMMIT}"]
    for n in sorted(set(want) | set(got)):
        if want.get(n) != got.get(n):
            probs.append(f"configuration file {n}: built from {str(got.get(n))[:12]}, "
                         f"repository has {str(want.get(n))[:12]}")
    return probs


def run_elf(vvp, elf, name, work, stress=None):
    if stress is not None:
        work = work / f"stress{stress}"
    work.mkdir(parents=True, exist_ok=True)
    r = subprocess.run([sys.executable, str(ROOT / "scripts/compliance/elf2mem.py"), str(elf),
                        str(work / "image.hex")], capture_output=True, text=True)
    if r.returncode != 0:
        return "fail", "image: " + (r.stdout + r.stderr).strip()
    args = [rt.VVP, "-n", str(vvp), f"+image={work / 'image.hex'}", f"+tohost={HALT}",
            f"+console={CONSOLE}", f"+name={name}", f"+trace={work / 'trace.txt'}"]
    if stress is not None:
        args.append(f"+stress={stress}")
    try:
        p = subprocess.run(args, capture_output=True, text=True, timeout=rt.WALL_LIMIT, cwd=ROOT)
    except subprocess.TimeoutExpired:
        return "fail", f"wall-clock limit {rt.WALL_LIMIT} s"
    out = p.stdout + p.stderr
    (work / "run.log").write_text(out)
    lines = [ln for ln in out.splitlines() if re.match(r"^(PASS|FAIL|TIMEOUT) tb_compliance ", ln)]
    console_fail = [ln for ln in out.splitlines() if "RVCP-SUMMARY: TEST FAILED" in ln]
    console_pass = [ln for ln in out.splitlines() if "RVCP-SUMMARY: TEST PASSED" in ln]
    ok = (p.returncode == 0 and len(lines) == 1 and lines[0].startswith(f"PASS tb_compliance {name} ")
          and len(console_pass) == 1 and not console_fail
          and not re.search(r"^(ERROR|FATAL|FAIL|TIMEOUT)", out, re.M))
    detail = (console_fail or lines or out.strip().splitlines()[-1:] or ["no result line"])[0]
    if lines and lines[0].startswith("PASS") and len(console_pass) != 1 and not console_fail:
        detail = f"halted with the pass value but printed {len(console_pass)} passing summary lines"
    return ("pass" if ok else "fail"), detail


def run_test(vvp, elf, name, work, stress):
    st, det = run_elf(vvp, elf, name, work)
    if st == "pass" and stress is not None:
        st, det2 = run_elf(vvp, elf, name, work, stress)
        det = det if st == "pass" else f"stress{stress}: {det2}"
    return st, det


def selftest(vvp):
    fx = ROOT / "sw/compliance/selftest/act4"
    link = ROOT / "sw/compliance/act4/px32/link.ld"
    expect = {"act_pass": "pass", "act_fail": "fail", "act_console_fail": "fail", "act_nohalt": "fail",
              "act_silent_pass": "fail"}
    ok = True
    for t, want in expect.items():
        work = OUT / "selftest" / t
        work.mkdir(parents=True, exist_ok=True)
        elf = work / f"{t}.elf"
        c = subprocess.run([str(rt.GCC), "-march=rv32imc_zicsr_zifencei", "-mabi=ilp32", "-nostdlib",
                            "-nostartfiles", f"-T{link}", str(fx / f"{t}.S"), "-o", str(elf)],
                           capture_output=True, text=True)
        if c.returncode != 0:
            print(c.stdout + c.stderr)
            got, det = "fail", "build failed"
        else:
            got, det = run_elf(vvp, elf, t, work)
        good = got == want
        ok &= good
        print(f"  selftest {t:<18} expected {want:<5} got {got:<5} {'ok' if good else 'MISMATCH'}  {det}")
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--suite", type=Path, default=Path("C:/px32-tools/src/riscv-arch-test"))
    ap.add_argument("--elf-dir", type=Path)
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--stress", type=int, default=None)
    a = ap.parse_args()
    vvp = rt.compile_bench()
    if a.selftest:
        ok = selftest(vvp)
        print("PASS act4 runner selftest" if ok else "FAIL act4 runner selftest")
        return 0 if ok else 1
    head = rt.git_head(a.suite)
    if head != SUITE_COMMIT:
        sys.exit(f"FAIL riscv-arch-test at {head}, expected {SUITE_COMMIT}")
    if not a.elf_dir or not a.elf_dir.is_dir():
        sys.exit("FAIL no --elf-dir with built ELFs")
    stale = manifest_problems(a.elf_dir)
    if stale:
        sys.exit("FAIL stale or unidentified ELF set:\n  " + "\n  ".join(stale))
    elfs = {p.stem: p for p in a.elf_dir.rglob("*.elf")}
    results, ok, used = [], True, set()
    for g in REQUIRED:
        srcs = sorted(p.stem for p in (a.suite / "tests/rv32i" / g).glob("*.S"))
        res = {"group": g, "sources": len(srcs), "tests": []}
        if not srcs:
            res["problem"] = "no sources"
            ok = False
        print(f"{g}:", flush=True)
        for t in srcs:
            if t not in elfs:
                st, det = "fail", "no ELF built"
            else:
                used.add(t)
                st, det = run_test(vvp, elfs[t], t, OUT / g / t, a.stress)
            res["tests"].append({"test": t, "result": st, "detail": det})
            print(f"  {t:<34} {st.upper():<5} {det}", flush=True)
            ok &= st == "pass"
        results.append(res)
    extra = sorted(set(elfs) - used)
    info = {"group": "other (informational)", "sources": len(extra), "tests": []}
    for t in extra:
        st, det = run_test(vvp, elfs[t], t, OUT / "other" / t, a.stress)
        info["tests"].append({"test": t, "result": st, "detail": det})
        print(f"  (info) {t:<27} {st.upper():<5} {det}", flush=True)
    results.append(info)
    mode = "ideal memory" if a.stress is None else f"ideal memory and stress seed {a.stress}"
    lines = [f"riscv-arch-test {SUITE_COMMIT} (4.1.0, ACT4), {mode}",
             f"{'group':<10} {'sources':>7} {'pass':>5} {'fail':>5}"]
    for r in results:
        n = sum(x["result"] == "pass" for x in r["tests"])
        lines.append(f"{r['group']:<10} {r['sources']:>7} {n:>5} {len(r['tests']) - n:>5}")
    lines.append(("PASS" if ok else "FAIL") + " riscv-arch-test (required: " + ", ".join(REQUIRED) + ")")
    print("\n".join(lines))
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "summary.txt").write_text("\n".join(lines) + "\n")
    (OUT / "results.json").write_text(json.dumps({"suite_commit": SUITE_COMMIT, "groups": results}, indent=1))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
