# rvmodel_macros.h: RVMODEL macros for PX32 (riscv-arch-test 4.1.0, ACT4).
# Generated by scripts/compliance/make_act4_config.py; NOT VALIDATED by the framework yet.
# Halting uses the tb_compliance tohost protocol: store 1 (pass) or 3 (fail) to the halt
# word; the bench ends the simulation on that store. Console: byte stores to 0x100ffff8.

#ifndef _RVMODEL_MACROS_H
#define _RVMODEL_MACROS_H

#define RVMODEL_DATA_SECTION

#define STANDARD_SM_SUPPORTED

# Unmapped address: PX32 raises a load/store access fault (bus error, contract section 3.2).
#define RVMODEL_ACCESS_FAULT_ADDRESS 0x30000000

#define RVMODEL_HALT_PASS  \
  li x1, 1                ;\
  li t0, 0x100ffff0     ;\
  write_halt_pass:        ;\
    sw x1, 0(t0)          ;\
  self_loop_pass:         ;\
    j self_loop_pass      ;\

#define RVMODEL_HALT_FAIL \
  li x1, 3                ;\
  li t0, 0x100ffff0     ;\
  write_halt_fail:        ;\
    sw x1, 0(t0)          ;\
  self_loop_fail:         ;\
    j self_loop_fail      ;\

#define RVMODEL_IO_WRITE_STR(_R1, _R2, _R3, _STR_PTR) \
1:                           ;                        \
  lbu  _R1, 0(_STR_PTR)      ;                        \
  beqz _R1, 3f               ;                        \
  li   _R2, 0x100ffff8  ;                        \
  sb   _R1, 0(_R2)           ;                        \
  addi _STR_PTR, _STR_PTR, 1 ;                        \
  j 1b                       ;                        \
3:

# Interrupt delays (cycles): required by tests/env/check_defines.h for every test, used only
# by interrupt tests, which are excluded in Phase 1. Upstream CVA6/CV32E20/CV32E40X values.
#define RVMODEL_INTERRUPT_LATENCY 10
#define RVMODEL_TIMER_INT_SOON_DELAY 100

# No interrupt sources before Phase 2 (CLIC): interrupt tests are excluded from the build
# (setup_act4_wsl.sh); the macros stay empty.
#define RVMODEL_SET_MEXT_INT(_R1, _R2)
#define RVMODEL_CLR_MEXT_INT(_R1, _R2)
#define RVMODEL_SET_MSW_INT(_R1, _R2)
#define RVMODEL_CLR_MSW_INT(_R1, _R2)
#define RVMODEL_SET_SEXT_INT(_R1, _R2)
#define RVMODEL_CLR_SEXT_INT(_R1, _R2)
#define RVMODEL_SET_SSW_INT(_R1, _R2)
#define RVMODEL_CLR_SSW_INT(_R1, _R2)

#endif // _RVMODEL_MACROS_H
