#!/usr/bin/env bash
# Drift check for the committed golden vectors (pre-Phase 2 audit E-07).
#
# The unit-test vectors under tb/unit/vectors are generated by Python models from fixed
# seeds and committed, so regression needs no Python. This script regenerates them in
# place and fails if any file differs from the committed version, which would mean the
# models and the committed vectors have drifted apart. The decoder and decompressor
# generators also cross-check their models against the GNU disassembler, so the RISC-V
# toolchain must be installed (RISCV_BIN or the xPack default).
#
# Usage: bash scripts/check_vectors.sh   (exit 0: no drift)

set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
PY="${PYTHON:-${LOCALAPPDATA:-}/Programs/Python/Python312/python.exe}"
[ -x "$PY" ] || PY="$(command -v python3 || command -v python)"

if ! git diff --quiet -- tb/unit/vectors; then
  echo "FAIL check_vectors: tb/unit/vectors has uncommitted changes; commit or revert them first"
  exit 1
fi
for gen in gen_alu_vectors gen_decoder_vectors gen_decompressor_vectors; do
  "$PY" "scripts/$gen.py" > "sim/check_vectors_$gen.log" 2>&1 || {
    echo "FAIL check_vectors: scripts/$gen.py failed (sim/check_vectors_$gen.log)"; exit 1; }
done
if git diff --quiet -- tb/unit/vectors; then
  echo "PASS check_vectors: regenerated vectors are identical to the committed ones"
else
  git diff --stat -- tb/unit/vectors
  echo "FAIL check_vectors: regenerated vectors differ from the committed ones (drift)"
  exit 1
fi
